// cpp standard libs
#include <iostream>

//vcd dump
#include "verilated_vcd_c.h"
#include "verilated.h"

#include "Vbaud_generator_int.h"        // Generated by Verilator

int main(int argc, char **argv) 
{
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    //Module
    Vbaud_generator_int* top = new Vbaud_generator_int;

    //VCD object to write
    VerilatedVcdC* vcd=new VerilatedVcdC;

    top->trace(vcd,99);
    vcd->open("dump.vcd");

    int sysClk = 0;
    int nRst = 0;

    top->baudDivisor=64;
    top->baudOversampling=0x04;
    top->nRst=nRst;
    //initial eval
    top->eval();

    nRst=1;
    top->nRst=nRst;

    for(int i=0;i<1024*4;i++)
    {
        sysClk=!sysClk;

        //update signals
        top->sysClk=sysClk;
        top->nRst=nRst;

        //evaluate
        top->eval();
        
        vcd->dump(i);
    }

    vcd->close();

    //cleanup
    delete top;
    delete vcd;
    return 0;
}