// cpp standard libs
#include <iostream>

//vcd dump
#include "verilated_vcd_c.h"
#include "verilated.h"

#include "Vuart_tx.h"        // Generated by Verilator

// //Driver generates 8-bit randomized values
// #include "uart_tx_driver.hpp"

int main(int argc, char **argv) 
{
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    //Module
    Vuart_tx* top = new Vuart_tx;

    //VCD object to write
    VerilatedVcdC* vcd=new VerilatedVcdC;

    top->trace(vcd,99);
    vcd->open("dump.vcd");

    int baudClk=1;
    int nRst=0;

    top->dataTx=0x5A;
    top->parity=0;
    top->stopBits=0;

    for(int i=0;i<1024;i++)
    {
        if(i<16)
        {
            if(i<8)
            {
                top->startTx=0b1;
                top->nRst=0;
            }
            else
                top->nRst=1;
        }
        else
            top->startTx=0;

        baudClk=!baudClk;

        //update signals
        top->baudClk=baudClk;
        top->nRst=nRst;

        //evaluate
        top->eval();
        
        vcd->dump(i);
    }

    vcd->close();

    //cleanup
    delete top;
    delete vcd;
    return 0;
}