// cpp standard libs
#include <iostream>

// vcd dump
#include "verilated_vcd_c.h"
#include "verilated.h"

#include "Vuart_core.h"        // Generated by Verilator

// Register map for uart core
#include "uart_core_reg_mem.hpp"

// global references for now
VerilatedVcdC* vcd;
Vuart_core* top;

void tick(int* timestamp)
{
    top->sysClk=!top->sysClk;
    (*timestamp)++;
    top->eval();
    vcd->dump(*timestamp);

    top->sysClk=!top->sysClk;
    (*timestamp)++;
    top->eval();
    vcd->dump(*timestamp);
}

int main(int argc, char **argv)
{
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    // Module
    top=new Vuart_core;

    // VCD object to write
    vcd=new VerilatedVcdC;

    top->trace(vcd,99);
    vcd->open("dump.vcd");

    int nRst=0;

    // timestamp i
    int i=0;

    // init clock
    top->sysClk=0;

    // tick for 16 cycles with reset(active low)
    for(i=0;i<16;i++)
    {
        top->nRst=nRst;
        tick(&i);
    }

    nRst=1;
    int prevI=i;

    // tick for 4 cycles with reset off (high)
    for (;i<prevI+4;i++)
    {
        top->nRst=nRst;
        tick(&i);
    }

    // set config
    top->addrIn=UART_REG_CONFIG_OFF;
    top->dataIn=0x00010002;
    top->wr=1;
    tick(&i);
    top->wr=0;
    tick(&i);

    // set write
    top->addrIn=UART_REG_WRITE_OFF;
    top->dataIn=0x0000005A;
    top->wr=1;
    tick(&i);
    top->wr=0;
    tick(&i);

    // start uart
    top->addrIn=UART_REG_CONTROL_OFF;
    top->dataIn=0x00000001;
    top->wr=1;
    tick(&i);
    top->wr=0;
    tick(&i);

    // //run until uart is free
    int status;

    top->addrIn=UART_REG_STATUS_OFF;
    top->wr=0;
    tick(&i);
    status=top->dataOut;
    
    while(status==1)
    {
        top->addrIn=UART_REG_STATUS_OFF;
        top->wr=0;
        tick(&i);
        status=top->dataOut;
    }

    // set write
    top->addrIn=UART_REG_WRITE_OFF;
    top->dataIn=0x00000036;
    top->wr=1;
    tick(&i);
    top->wr=0;
    tick(&i);

    // start uart
    top->addrIn=UART_REG_CONTROL_OFF;
    top->dataIn=0x00000001;
    top->wr=1;
    tick(&i);
    top->wr=0;
    tick(&i);

    for(int j=0;j<256;j++)
    {
        tick(&i);
    }

    vcd->close();

    // cleanup
    delete top;
    delete vcd;

    return 0;
}